name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop, 'support/**' ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/*, feature/RDK*, develop, 'support/**' ]

jobs:
  build-entservices-on-pr:
    name: Build iarmmgrs component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          sh -x build_dependencies.sh
          sh -x cov_build.sh